### ISSUE TITLE
KUSTO_DATABASE Parameter Field Not Recognized

### ISSUE THREAD

**Issue by richterxela** [Azure/azure-kusto-spark#180]
Using library version spark-kusto-connector:2.3.1

The spark read connector is not recognizing the value I give for the 'KUSTO_DATABASE' parameter. Attempting to read from a Kusto datasource, the error seems to imply a destination DB is also required but we are not trying to write to a Kusto database.

Current format. Replaced the database field directly with the database name I wanted to use to test, the other fields are populated via config.
kusto_df = spark.read. \
    format("com.microsoft.kusto.spark.datasource"). \
    option("KUSTO_CLUSTER", kustoOptions["KUSTO_CLUSTER"]). \
    option("KUSTO_DATABASE", 'defaultdb'). \
    option("KUSTO_TABLE", kustoOptions["KUSTO_TABLE"]). \
    option("KUSTO_AAD_APP_ID", kustoOptions["KUSTO_AAD_APP_ID"]). \
    option("KUSTO_AAD_APP_SECRET", kustoOptions["KUSTO_AAD_APP_SECRET"]). \
    option("KUSTO_AAD_AUTHORITY_ID", kustoOptions["KUSTO_AAD_AUTHORITY_ID"]). \
    option("blobStorageAccountName", kustoOptions["blobStorageAccountName"]). \
    option("blobStorageAccountKey", kustoOptions["blobStorageAccountKey"]). \
    option("blobContainer", kustoOptions["blobContainer"]). \
    option("clientRequestPropertiesJson", crp.toString()). \
    load() 

Error output:
Py4JJavaError: An error occurred while calling o9544.load.
: java.security.InvalidParameterException: KUSTO_DATABASE parameter is missing. Must provide a destination database name
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.parseSourceParameters(KustoDataSourceUtils.scala:100)
	at com.microsoft.kusto.spark.datasource.DefaultSource.createRelation(DefaultSource.scala:88)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:385)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:424)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$3(DataFrameReader.scala:391)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:391)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)

**Comment by ohadbitt** [comment]
hi the strings are a little different "kustoDatabase" . KUSTO_DATABASE is part of the saved option but is available only in scala - please see the pyspark sample
https://github.com/Azure/azure-kusto-spark/tree/master/samples/src/main/python
