### ISSUE TITLE
Connector doesn't support cluster URL for Azure Monitoring when Kusto Explorer and Python SDK support it

### ISSUE THREAD

**Issue by softnado** [Azure/azure-kusto-spark#223]
**Describe the bug**
The Kusto Explorer and Python SDK able to connect to Azure Monitoring using the ADE URL defined here: https://docs.microsoft.com/en-us/azure/data-explorer/query-monitor-data#additional-syntax-examples but Kusto Spark Connector seems only support the standard https://clustername.regionname.kusto.windows.net format.

**To Reproduce**
spark.read \
            .format("com.microsoft.kusto.spark.synapse.datasource") \
            .option("spark.synapse.linkedService", "Linked Service Name to https://ade.applicationinsights.io/subscriptions/ABCDEFG/resourcegroups/monitoring/providers/microsoft.insights/components/abcdefg)") \
            .option("kustoDatabase", "abcdefg") \
            .option("kustoQuery", "customEvents|count") \
            .load()

**Exception**
Py4JJavaError: An error occurred while calling o223.load.
: java.security.InvalidParameterException: KUSTO_CLUSTER parameter accepts either a full url with https scheme or the cluster'salias and tries to construct the full URL from it. Parameter given: https://ade.applicationinsights.io/subscriptions/ABCDEFG/resourcegroups/monitoring/providers/microsoft.insights/components/abcdefg
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.getClusterNameFromUrlIfNeeded(KustoDataSourceUtils.scala:308)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.parseSourceParameters(KustoDataSourceUtils.scala:119)
	at com.microsoft.kusto.spark.datasource.DefaultSource.createRelation(DefaultSource.scala:88)
	at com.microsoft.kusto.spark.synapse.datasource.BaseDefaultSource.super$createRelation(DefaultSource.scala:33)
	at com.microsoft.kusto.spark.synapse.datasource.BaseDefaultSource.$anonfun$createRelation$2(DefaultSource.scala:33)
	at com.microsoft.kusto.spark.synapse.utils.ComponentEventPublisherEx$.$anonfun$publishComponentEventFor$1(AppEventPublisher.scala:66)
	at scala.util.Try$.apply(Try.scala:213)
	at com.microsoft.spark.utils.CommonUtils$.executeFunction(CommonUtils.scala:55)

**Expected behavior**
Expect it to connect and return the query result.

**Comment by yogilad** [comment]
@ohadbitt , do you think this has a chance of working?
Ingest for instance requires some special management commands which are not available in AM,

**Comment by initions-erb** [comment]
Any update on this? - Is there a example on how to connect to log analytics?

**Comment by ohadbitt** [comment]
Fixed in 3.0.0

**Comment by Sri-Bhashini** [comment]
Is this also fixed for log analytics?

**Comment by ag-ramachandran** [comment]
Hello @Sri-Bhashini , yes LA workspace tables can be queried as well

**Comment by Sri-Bhashini** [comment]
Thanks @ag-ramachandran and is the 3.0.0 the spark version?
