### ISSUE TITLE
java.lang.NoClassDefFoundError: com/microsoft/aad/msal4j/ClientCredentialFactory

### ISSUE THREAD

**Issue by aayushsin** [Azure/azure-kusto-spark#248]
**Describe the bug**
Fail to write to Kusto (Azure Data Explore), on Spark Stream. Throwing the following exception. It works with the Synapse linked service while the default way with connector is not working .
``

**To Reproduce**
```python
df.write \
    .format("com.microsoft.kusto.spark.synapse.datasource") \
    .option("spark.synapse.linkedService", <CLUSTER>) \
    .option("kustoDatabase", <DATABASE>) \
    .option("kustoTable", <TABLE>) \
    .option("tableCreateOptions","CreateIfNotExist") \
    .mode("Append") \
    .save()
```
works like a charm

However, following is giving the error
```python
df.write \
    .format("com.microsoft.kusto.spark.synapse.datasource") \
    .option("kustoCluster",<CLUSTER>)\
    .option("kustoDatabase", <DATABASE>) \
    .option("kustoTable", <TABLE>) \
    .option("tableCreateOptions","CreateIfNotExist") \
    .option("kustoAadAppId", Client_id)\
    .option("kustoAadAppSecret", Client_Secret)\
    .option("kustoAadAuthorityID", AUTH_ID) \
    .mode("Append") \
    .save()
```

**Error**
```bash
Py4JJavaError: An error occurred while calling o728.save.
: java.lang.NoClassDefFoundError: com/microsoft/aad/msal4j/ClientCredentialFactory
	at com.microsoft.azure.kusto.data.auth.TokenProviderFactory.createTokenProvider(TokenProviderFactory.java:25)
	at com.microsoft.azure.kusto.data.ClientImpl.<init>(ClientImpl.java:53)
	at com.microsoft.azure.kusto.data.ClientFactory.createClient(ClientFactory.java:16)
	at com.microsoft.kusto.spark.utils.KustoClient.engineClient$lzycompute(KustoClient.scala:36)
	at com.microsoft.kusto.spark.utils.KustoClient.engineClient(KustoClient.scala:36)
	at com.microsoft.kusto.spark.datasink.KustoWriter$.write(KustoWriter.scala:60)
	at com.microsoft.kusto.spark.datasource.DefaultSource.createRelation(DefaultSource.scala:49)
	at com.microsoft.kusto.spark.synapse.datasource.BaseDefaultSource.super$createRelation(DefaultSource.scala:23)
	at com.microsoft.kusto.spark.synapse.datasource.BaseDefaultSource.$anonfun$createRelation$1(DefaultSource.scala:23)
	at com.microsoft.kusto.spark.synapse.utils.ComponentEventPublisherEx$.$anonfun$publishComponentEventFor$1(AppEventPublisher.scala:66)
	at scala.util.Try$.apply(Try.scala:213)
	at com.microsoft.spark.utils.CommonUtils$.executeFunction(CommonUtils.scala:55)
	at com.microsoft.spark.utils.CommonUtils$.getBlockTimeAndResult(CommonUtils.scala:36)
	at com.microsoft.kusto.spark.synapse.utils.ComponentEventPublisherEx$.publishComponentEventFor(AppEventPublisher.scala:65)
	at com.microsoft.kusto.spark.synapse.utils.EventPublisher.publishComponentEventFor(AppEventPublisher.scala:30)
	at com.microsoft.kusto.spark.synapse.datasource.BaseDefaultSource.createRelation(DefaultSource.scala:20)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:218)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:256)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:253)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:214)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:148)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:147)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:1013)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:181)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:94)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:68)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:1013)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:462)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:434)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:303)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.microsoft.aad.msal4j.ClientCredentialFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 48 more

```

pip list
```
Package                       Version
----------------------------- -------------------
absl-py                       0.13.0
adal                          1.2.7
adlfs                         0.7.7
aiohttp                       3.7.4.post0
appdirs                       1.4.4
applicationinsights           0.11.10
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
astor                         0.8.1
astunparse                    1.6.3
async-timeout                 3.0.1
attrs                         21.2.0
azure-common                  1.1.27
azure-core                    1.24.2
azure-datalake-store          0.0.51
azure-graphrbac               0.61.1
azure-identity                1.6.1
azure-keyvault                4.1.0
azure-keyvault-certificates   4.4.0
azure-keyvault-keys           4.5.1
azure-keyvault-secrets        4.4.0
azure-kusto-data              3.1.3
azure-kusto-ingest            3.1.3
azure-mgmt-authorization      0.61.0
azure-mgmt-containerregistry  8.0.0
azure-mgmt-core               1.3.0
azure-mgmt-keyvault           2.2.0
azure-mgmt-resource           13.0.0
azure-mgmt-storage            19.0.0
azure-servicebus              7.0.0b7
azure-storage-blob            12.9.0
azure-storage-queue           12.4.0
azure-synapse-ml-predict      1.0.0
azureml-core                  1.34.0
azureml-dataprep              2.22.2
azureml-dataprep-native       38.0.0
azureml-dataprep-rslex        1.20.2
azureml-dataset-runtime       1.34.0
azureml-mlflow                1.34.0
azureml-opendatasets          1.34.0
azureml-synapse               0.0.1
azureml-telemetry             1.34.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
beautifulsoup4                4.9.3
bleach                        5.0.1
blinker                       1.4
bokeh                         2.3.2
Brotli                        1.0.9
brotlipy                      0.7.0
cachetools                    4.2.2
certifi                       2021.10.8
cffi                          1.14.5
chardet                       4.0.0
click                         8.0.1
cloudpickle                   1.6.0
conda-package-handling        1.7.3
configparser                  5.0.2
contextlib2                   0.6.0.post1
cryptography                  3.4.7
cycler                        0.10.0
Cython                        0.29.23
cytoolz                       0.11.0
dash                          1.20.0
dash-core-components          1.16.0
dash-cytoscape                0.2.0
dash-html-components          1.1.3
dash-renderer                 1.9.1
dash-table                    4.11.3
dask                          2021.6.2
databricks-cli                0.12.1
debugpy                       1.3.0
decorator                     4.4.2
defusedxml                    0.7.1
dill                          0.3.4
distlib                       0.3.4
distro                        1.7.0
docker                        4.4.4
dotnetcore2                   2.1.23
entrypoints                   0.3
et-xmlfile                    1.1.0
fastjsonschema                2.15.3
filelock                      3.7.1
fire                          0.4.0
Flask                         2.0.1
Flask-Compress                0.0.0
flatbuffers                   1.12
fsspec                        2021.6.1
fsspec-wrapper                0.1.5
fusepy                        3.0.1
future                        0.18.2
gast                          0.3.3
gensim                        3.8.3
geographiclib                 1.52
geopy                         2.1.0
gevent                        21.1.2
gitdb                         4.0.7
GitPython                     3.1.18
google-api-core               2.8.1
google-auth                   1.32.1
google-auth-oauthlib          0.4.1
google-pasta                  0.2.0
googleapis-common-protos      1.56.2
greenlet                      1.1.0
grpcio                        1.37.1
h5py                          2.10.0
html5lib                      1.1
hummingbird-ml                0.4.0
idna                          2.10
ijson                         3.1.4
imagecodecs                   2021.3.31
imageio                       2.9.0
importlib-metadata            4.6.1
importlib-resources           5.8.0
ipykernel                     6.0.1
ipython                       7.23.1
ipython-genutils              0.2.0
ipywidgets                    7.6.3
isodate                       0.6.0
itsdangerous                  2.0.1
jdcal                         1.4.1
jedi                          0.18.0
jeepney                       0.6.0
Jinja2                        3.0.1
jmespath                      0.10.0
joblib                        1.0.1
jsonpickle                    2.0.0
jsonschema                    4.6.1
jupyter-client                6.1.12
jupyter-core                  4.7.1
jupyterlab-pygments           0.2.2
jupyterlab-widgets            1.1.1
Keras-Applications            1.0.8
Keras-Preprocessing           1.1.2
keras2onnx                    1.6.5
kiwisolver                    1.3.1
koalas                        1.8.0
KqlmagicCustom                0.1.114.post8
liac-arff                     2.5.0
library-metadata-cooker       0.0.7
lightgbm                      3.2.1
lime                          0.2.0.1
llvmlite                      0.36.0
locket                        0.2.1
lxml                          4.6.5
Markdown                      3.3.4
MarkupSafe                    2.0.1
matplotlib                    3.4.2
matplotlib-inline             0.1.2
mistune                       0.8.4
mleap                         0.17.0
mlflow-skinny                 1.18.0
msal                          1.12.0
msal-extensions               0.3.0
msrest                        0.6.21
msrestazure                   0.6.4
multidict                     5.1.0
mypy                          0.780
mypy-extensions               0.4.3
nbclient                      0.6.6
nbconvert                     6.5.0
nbformat                      5.4.0
ndg-httpsclient               0.5.1
nest-asyncio                  1.5.5
networkx                      2.5.1
nltk                          3.6.2
notebook                      6.4.12
notebookutils                 3.1.2-20220617.6
numba                         0.53.1
numpy                         1.19.4
oauthlib                      3.1.1
olefile                       0.46
onnx                          1.9.0
onnxconverter-common          1.7.0
onnxmltools                   1.7.0
onnxruntime                   1.7.2
opencensus                    0.9.0
opencensus-context            0.1.2
opencensus-ext-azure          1.1.0
openpyxl                      3.0.7
opt-einsum                    3.3.0
packaging                     21.0
pandas                        1.2.3
pandasql                      0.7.3
pandocfilters                 1.5.0
parso                         0.8.2
partd                         1.2.0
pathspec                      0.8.1
patsy                         0.5.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.2.0
pip                           21.2.4
platformdirs                  2.5.2
plotly                        4.14.3
pmdarima                      1.8.2
pooch                         1.4.0
portalocker                   1.7.1
prettytable                   2.4.0
prometheus-client             0.14.1
prompt-toolkit                3.0.19
protobuf                      3.15.8
psutil                        5.8.0
ptyprocess                    0.7.0
py4j                          0.10.9
pyarrow                       3.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycairo                       1.20.1
pycosat                       0.6.3
pycparser                     2.20
Pygments                      2.9.0
PyGObject                     3.40.1
PyJWT                         2.1.0
pyodbc                        4.0.30
pyOpenSSL                     21.0.0
pyparsing                     2.4.7
pyperclip                     1.8.2
PyQt5                         5.12.3
PyQt5_sip                     4.19.18
PyQtChart                     5.12
PyQtWebEngine                 5.12.1
pyrsistent                    0.18.1
PySocks                       1.7.1
pyspark                       3.1.2
python-dateutil               2.8.1
pytz                          2021.1
pyu2f                         0.1.5
PyWavelets                    1.1.1
PyYAML                        5.4.1
pyzmq                         22.1.0
regex                         2021.7.6
requests                      2.25.1
requests-oauthlib             1.3.0
retrying                      1.3.3
rsa                           4.7.2
ruamel.yaml                   0.17.4
ruamel.yaml.clib              0.2.6
ruamel-yaml-conda             0.15.100
sai                           1.0.1.1653677083
SALib                         1.3.11
scikit-image                  0.18.1
scikit-learn                  0.23.2
scipy                         1.5.3
seaborn                       0.11.1
SecretStorage                 3.3.1
Send2Trash                    1.8.0
setuptools                    49.6.0.post20210108
shap                          0.39.0
six                           1.16.0
skl2onnx                      1.8.0
sklearn-pandas                2.2.0
slicer                        0.0.7
smart-open                    5.1.0
smmap                         3.0.5
soupsieve                     2.2.1
SQLAlchemy                    1.4.20
sqlanalyticsconnectorpy       1.0.0
statsmodels                   0.12.2
synapseml-cognitive           0.9.5.dev1
synapseml-core                0.9.5.dev1
synapseml-deep-learning       0.9.5.dev1
synapseml-lightgbm            0.9.5.dev1
synapseml-opencv              0.9.5.dev1
synapseml-vw                  0.9.5.dev1
tabulate                      0.8.9
tenacity                      8.0.1
tensorboard                   2.4.1
tensorboard-plugin-wit        1.8.0
tensorflow                    2.4.1
tensorflow-estimator          2.4.0
termcolor                     1.1.0
terminado                     0.15.0
textblob                      0.15.3
threadpoolctl                 2.1.0
tifffile                      2021.4.8
tinycss2                      1.1.1
toolz                         0.11.1
torch                         1.8.1
torchvision                   0.9.1
tornado                       6.1
tqdm                          4.61.2
traitlets                     5.3.0
typed-ast                     1.4.3
typing_extensions             4.3.0
uamqp                         1.5.3
urllib3                       1.26.4
virtualenv                    20.14.0
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.1.0
Werkzeug                      2.0.1
wheel                         0.36.2
widgetsnbextension            3.5.2
wrapt                         1.12.1
xgboost                       1.4.0
yarl                          1.6.3
zipp                          3.5.0
zope.event                    4.5.0
zope.interface                5.4.0
```
    

**Expected behavior**
Is it some issue with the spark jar files in Synapse studio?

**Comment by aayushsin** [comment]
Linked issue from last year: https://github.com/Azure/azure-kusto-spark/issues/212

**Comment by ohadbitt** [comment]
This usually rises when a user tries to work from Synapse using this repo connector coordinates.
Meaning using  `df.write.format("com.microsoft.kusto.spark.datasource")` instead of `spark.write.format("com.microsoft.kusto.spark.synapse.datasource")`
We intentionally don’t allow users to use the Spark connector coordinates here so that users authenticate with the Synapse token library.
For synapse usage go [here](https://github.com/Azure/azure-kusto-spark/blob/master/samples/src/main/python/SynapseSample.py) or [here](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/data-sources/apache-spark-kusto-connector)

**Comment by ag-ramachandran** [comment]
@aayushsin if this is no longer an issue can we close this

**Comment by vipinsorot** [comment]
@ohadbitt i am getting the same issue after version upgrade
**previous version**:com.microsoft.azure.kusto:kusto-spark_2.4_2.11:2.7.5
**current version**:com.microsoft.azure.kusto:kusto-spark_3.0_2.12:5.0.0 

Current ADB Cluster details:
 Apache Spark 3.3.2, Scala 2.12

Any suggestions how can i resolve this ASAP ?

**Comment by ag-ramachandran** [comment]
@vipinsorot 

To avoid this you can try out one of the below two:

Import the [Az identity](https://mvnrepository.com/artifact/com.azure/azure-identity/1.9.0) explicitly.

Try importing jar from the [official github](https://github.com/Azure/azure-kusto-spark/releases/tag/v3.0_5.0.0) release.
