### ISSUE TITLE
 DataServiceException: IOError when trying to retrieve CloudInfo

### ISSUE THREAD

**Issue by Sri-Bhashini** [Azure/azure-kusto-spark#289]
**Describe the bug**
I am trying to connect to Log Analytics workspace and trying to access the log table in the workspace. It was not working initially but is working with one of the clusters now:

Below code is creating the Dataframe.
testdf = spark.read. \
            format("com.microsoft.kusto.spark.datasource"). \
            option("kustoCluster", "https://ade.loganalytics.io/subscriptions/<>/resourcegroups/<>/providers/microsoft.operationalinsights/workspaces/<>"). \
            option("kustoDatabase", ""). \
            option("kustoQuery", "StorageBlobLogs"). \
            option("kustoAadAppId", ""). \
            option("kustoAadAppSecret", ""). \
            option("kustoAadAuthorityID", ""). \
            load()
When I switched between Tenant name and Tenant ID it was initially working only for tenant name but now it seems to work for ID as well. 

When I try to display this dataframe, it throws error.

**To Reproduce**
testdf = spark.read. \
            format("com.microsoft.kusto.spark.datasource"). \
            option("kustoCluster", "https://ade.loganalytics.io/subscriptions/<>/resourcegroups/<>/providers/microsoft.operationalinsights/workspaces/<>"). \
            option("kustoDatabase", ""). \
            option("kustoQuery", "StorageBlobLogs"). \
            option("kustoAadAppId", ""). \
            option("kustoAadAppSecret", ""). \
            option("kustoAadAuthorityID", ""). \
            load()
display(testdf)

Error:

DataServiceException: IOError when trying to retrieve CloudInfo
com.microsoft.azure.kusto.data.exceptions.DataServiceException: IOError when trying to retrieve CloudInfo
	at com.microsoft.azure.kusto.data.auth.CloudInfo.retrieveCloudInfoForCluster(CloudInfo.java:122)
	at com.microsoft.azure.kusto.data.auth.CloudDependentTokenProviderBase.initialize(CloudDependentTokenProviderBase.java:31)
	at com.microsoft.azure.kusto.data.auth.CloudDependentTokenProviderBase.acquireAccessToken(CloudDependentTokenProviderBase.java:45)
	at com.microsoft.azure.kusto.data.ClientImpl.generateIngestAndCommandHeaders(ClientImpl.java:291)
	at com.microsoft.azure.kusto.data.ClientImpl.executeToJsonResult(ClientImpl.java:146)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:106)
	at com.microsoft.kusto.spark.utils.ExtendedKustoClient.$anonfun$executeDM$1(ExtendedKustoClient.scala:391)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$$anon$2.apply(KustoDataSourceUtils.scala:399)
	at io.github.resilience4j.retry.Retry.lambda$decorateCheckedSupplier$3f69f149$1(Retry.java:137)
	at io.github.resilience4j.retry.Retry.executeCheckedSupplier(Retry.java:419)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.retryApplyFunction(KustoDataSourceUtils.scala:402)
	at com.microsoft.kusto.spark.utils.ExtendedKustoClient.executeDM(ExtendedKustoClient.scala:392)
	at com.microsoft.kusto.spark.utils.ContainerProvider.refresh(ContainerProvider.scala:52)
	at com.microsoft.kusto.spark.utils.ContainerProvider.getAllContainers(ContainerProvider.scala:46)
	at com.microsoft.kusto.spark.utils.ExtendedKustoClient.getTempBlobsForExport(ExtendedKustoClient.scala:127)
	at com.microsoft.kusto.spark.datasource.KustoRelation.$anonfun$buildScanImpl$3(KustoRelation.scala:127)
	at scala.Option.getOrElse(Option.scala:189)
	at com.microsoft.kusto.spark.datasource.KustoRelation.buildScanImpl(KustoRelation.scala:127)
	at com.microsoft.kusto.spark.datasource.KustoRelation.buildScan(KustoRelation.scala:75)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.$anonfun$apply$3(DataSourceStrategy.scala:383)
        at org.apache.spark.sql.execution.datasources.DataSourceStrategy.$anonfun$pruneFilterProject$1(DataSourceStrategy.scala:417)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:472)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:416)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:383)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:67)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:489)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:97)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:74)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$3(QueryPlanner.scala:82)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:79)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:97)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:74)
	at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:427)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:124)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:124)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:117)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executedPlan$1(QueryExecution.scala:139)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:171)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:171)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:135)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:131)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$writePlans$5(QueryExecution.scala:248)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$.append(QueryPlan.scala:585)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$writePlans(QueryExecution.scala:248)
	at org.apache.spark.sql.execution.QueryExecution.toString(QueryExecution.scala:256)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$5(SQLExecution.scala:135)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:275)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:127)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:845)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:225)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3707)
	at org.apache.spark.sql.Dataset.collectResult(Dataset.scala:2984)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation0(OutputAggregator.scala:194)
	at com.databricks.backend.daemon.driver.OutputAggregator$.withOutputAggregation(OutputAggregator.scala:57)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.generateTableResult(PythonDriverLocal.scala:1292)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.$anonfun$getResultBufferInternal$1(PythonDriverLocal.scala:1204)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.withInterpLock(PythonDriverLocal.scala:991)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.getResultBufferInternal(PythonDriverLocal.scala:1073)
	at com.databricks.backend.daemon.driver.DriverLocal.getResultBuffer(DriverLocal.scala:556)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.outputSuccess(PythonDriverLocal.scala:1033)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.$anonfun$repl$8(PythonDriverLocal.scala:518)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.withInterpLock(PythonDriverLocal.scala:991)
	at com.databricks.backend.daemon.driver.PythonDriverLocal.repl(PythonDriverLocal.scala:505)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$10(DriverLocal.scala:449)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:47)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:269)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:47)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:426)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:653)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:645)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:486)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:598)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:391)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:337)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:219)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.UnknownHostException: ingest-ade.loganalytics.io: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1330)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1283)
	at java.net.InetAddress.getAllByName(InetAddress.java:1199)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.microsoft.azure.kusto.data.auth.CloudInfo.retrieveCloudInfoForCluster(CloudInfo.java:95)
	... 100 more

**Expected behavior**
Return Dataframe result.

**Comment by Sri-Bhashini** [comment]
It is working fine when I limit to 5000 rows. However, for a kusto cluster, the connector is able to retrieve large volume of data. Only log analytics is throwing this issue. Is it limited to 5000 only rows?

**Comment by ag-ramachandran** [comment]
Are there any limits to the LogAnalytics workspaces. As I understand, the connector can connect and retrieve data, but fails if there are more than 5000 rows. Is this a right statement ?


![image](https://user-images.githubusercontent.com/106139410/217987430-7669c944-34f8-4c46-ada8-50b09959ef9b.png)

The limits are 500k rows or 104MB of data for query API on LA/AzureMonitor. Could we perhaps try and retrieve a handful of columns to limit size of data and may be start investigating from there ?

https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits

**Comment by Sri-Bhashini** [comment]
Yes, that's the right statement. I have tried retrieving only 1 column and also tried bringing all columns. In both the cases, its allowing only 5000 rows. I dont think it is related to size.

**Comment by ag-ramachandran** [comment]
Hello @Sri-Bhashini , Raises the suspicion that it may be not related to connectivity of the connector and may be something specific to LA (query limits). We'd check this out and see if we can replicate
