### ISSUE TITLE
Getting error while querying kusto query in log analytics from databricks workspace

### ISSUE THREAD

**Issue by Sandeepvirkar** [Azure/azure-kusto-spark#405]
We are trying to query log analtics tables using databricks. We have established connection between databricks and log analytics workspace using service principle. We are able to query the table with intake value 4000. But if we increase intake value more than 5000. It is failing with the error. We checked this with internal network team. there is no network issue. But we are not able to understand strange behavior for intake value more than 5000. We are using below code in databricks. 

subscription = ""
resource_group = ""
log_analytics_workspace = ""
client_id = ""
client_secret = dbutils.secrets.get(scope="",key="")
tenant_id = ""
****
df = spark.read.format("com.microsoft.kusto.spark.datasource") \
    .option("kustoCluster", f"https://ade.loganalytics.io/subscriptions/{subscription}/resourceGroups/{resource_group}/providers/Microsoft.OperationalInsights/workspaces/{log_analytics_workspace}") \
    .option("kustoDatabase", log_analytics_workspace) \
    .option("kustoQuery", "AADManagedIdentitySignInLogs | take **4000**") \
    .option("kustoAadAppId", client_id) \
    .option("kustoAadAppSecret", client_secret) \
    .option("kustoAadAuthorityID", tenant_id) \
    .option("KustoSourceOptions.KUSTO_READ_MODE", "ForceSingleMode") \
    .load()

display(df) 

**Error message when take value is greater than 5000**.

com.microsoft.azure.kusto.data.exceptions.DataServiceException: IOException when trying to retrieve cluster metadata:ingest-ade.loganalytics.io: Name or service not known

**Comment by ag-ramachandran** [comment]
Hello @Sandeepvirkar 

Will have a look, the connector itself does not have an issue with the count. With LA , I will try and do a replication though.

What version of the connector do you use ? I will start from there and have a look

**Comment by pregress** [comment]
Still getting this error when using `ForceDistributedMode` 
With the latest version:  https://github.com/Azure/azure-kusto-spark/releases/tag/v3.0_5.2.7

Only with larger result sets

**Comment by ag-ramachandran** [comment]
@pregress, I am not sure how the LAWS behaves when looking for transient storage to export data in DistributedMode, In distributed mode, to get to a storage account we have to use some queries on the DM (ingest cluster)

Please use the [TransientStorageParameters](https://github.com/Azure/azure-kusto-spark/blob/v3.0_5.2.7/docs/KustoSource.md#transient-storage-parameters) option: to specify a storage for exporting the data in ForceDistributedMode and check if that works

**Comment by pregress** [comment]
Using the `transientStorage` option results in different errors, both with impersonate and a SAS uri.
Blob container exists, and rbac roles where created (Storage Blob Delegator & Storage Blob Data Contributor)

Tried both:
```
transientStorage = "{\"storageCredentials\": [{\"storageAccountName\": \"mystorageaccount\",\"blobContainer\": \"kusto\",\"sasUrl\": \"https://mystorageaccount.blob.core.windows.net/kusto;impersonate\"}],  \"endpointSuffix\": \"core.windows.net\"}"
```

and: 
```
transientStorage = "{\"storageCredentials\": [{\"storageAccountName\": \"mystorageaccount\",\"blobContainer\": \"kusto\",\"sasUrl\": \"https://mystorageaccount.blob.core.windows.net/kusto?sp=racwdl&st=2025-04-16T05:17:54Z&se=2025-04-20T13:17:54Z&spr=https&sv=2024-11-04&sr=c&sig=REDACTED%3D\"}], \"endpointSuffix\": \"core.windows.net\"}"
```




> Py4JJavaError: An error occurred while calling o549.showString.
: org.apache.spark.SparkException: [INTERNAL_ERROR] The Spark SQL phase planning failed with an internal error. You hit a bug in Spark or the Spark plugins you use. Please, report this bug to the corresponding communities or vendors, and provide the full stack trace. SQLSTATE: XX000
	at org.apache.spark.SparkException$.internalError(SparkException.scala:114)
	at org.apache.spark.sql.execution.QueryExecution$.toInternalError(QueryExecution.scala:1166)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1179)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:611)
	at com.databricks.util.LexicalThreadLocal$Handle.runWith(LexicalThreadLocal.scala:63)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:607)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1261)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:607)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhaseWithTracker$1(QueryExecution.scala:624)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:211)
	at org.apache.spark.sql.execution.QueryExecution.executePhaseWithTracker(QueryExecution.scala:624)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:535)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:531)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$_executedPlan$1(QueryExecution.scala:554)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1261)
	at org.apache.spark.sql.execution.QueryExecution._executedPlan$lzycompute(QueryExecution.scala:554)
	at org.apache.spark.sql.execution.QueryExecution._executedPlan(QueryExecution.scala:549)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:577)
	at org.apache.spark.sql.execution.QueryExecution.simpleString(QueryExecution.scala:661)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$explainString(QueryExecution.scala:725)
	at org.apache.spark.sql.execution.QueryExecution.explainStringLocal(QueryExecution.scala:689)
	at org.apache.spark.sql.execution.QueryExecution.explainString(QueryExecution.scala:682)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$10(SQLExecution.scala:406)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:759)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId0$1(SQLExecution.scala:335)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1261)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId0(SQLExecution.scala:206)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:696)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4845)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:3584)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:3815)
	at org.apache.spark.sql.Dataset.getRows(Dataset.scala:437)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:473)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:397)
	at py4j.Gateway.invoke(Gateway.java:306)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "secret" is null
	at com.microsoft.kusto.spark.utils.KustoAzureFsSetupCache$.updateAndGetPrevStorageAccountAccess(KustoAzureFsSetupCache.scala:24)
	at com.microsoft.kusto.spark.utils.KustoAzureFsSetupCache$.updateAndGetPrevSas(KustoAzureFsSetupCache.scala:42)
	at com.microsoft.kusto.spark.datasource.KustoReader$.$anonfun$setupBlobAccess$1(KustoReader.scala:255)
	at com.microsoft.kusto.spark.datasource.KustoReader$.$anonfun$setupBlobAccess$1$adapted(KustoReader.scala:240)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.microsoft.kusto.spark.datasource.KustoReader$.setupBlobAccess(KustoReader.scala:240)
	at com.microsoft.kusto.spark.datasource.KustoReader$.exportToStorage(KustoReader.scala:186)
	at com.microsoft.kusto.spark.datasource.KustoReader$.distributedBuildScan(KustoReader.scala:134)
	at com.microsoft.kusto.spark.datasource.KustoRelation.buildScanImpl(KustoRelation.scala:188)
	at com.microsoft.kusto.spark.datasource.KustoRelation.buildScan(KustoRelation.scala:100)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$apply$3(DataSourceStrategy.scala:517)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.$anonfun$pruneFilterProject$1(DataSourceStrategy.scala:552)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProjectRaw(DataSourceStrategy.scala:632)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.pruneFilterProject(DataSourceStrategy.scala:551)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$.apply(DataSourceStrategy.scala:517)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$2(QueryPlanner.scala:78)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$1(QueryPlanner.scala:78)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:119)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:107)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$5(QueryPlanner.scala:104)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1431)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.$anonfun$plan$4(QueryPlanner.scala:101)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:119)
	at org.apache.spark.sql.execution.SparkStrategies.plan(SparkStrategies.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$.createSparkPlan(QueryExecution.scala:1112)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$sparkPlan$1(QueryExecution.scala:538)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:94)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:509)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$5(QueryExecution.scala:612)
	at org.apache.spark.sql.execution.SQLExecution$.withExecutionPhase(SQLExecution.scala:145)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$4(QueryExecution.scala:612)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:1177)
	... 42 more
File <command-7203119687444253>, line 24
     13 #ForceSingleMode
     14 df = spark.read.format("com.microsoft.kusto.spark.datasource") \
     15     .option("kustoCluster", "[https://ade.loganalytics.io/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.OperationalInsights/workspaces/REDACTED](https://adb-5398508093614803.3.azuredatabricks.net/editor/notebooks/%3Ca%20class=)" target="_blank" rel="noopener noreferrer">[https://ade.loganalytics.io/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.OperationalInsights/workspaces/REDACTED</a></span><span>&quot;</span>](https://ade.loganalytics.io/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.OperationalInsights/workspaces/REDACTED%3C/a%3E%3C/span%3E%3Cspan%3E&quot;%3C/span%3E)) \
     16     .option("kustoDatabase", "REDACTED") \
   (...)
     21     .option("transientStorage", transientStorage) \
     22     .load()
---> 24 df.show()
File /databricks/spark/python/pyspark/instrumentation_utils.py:47, in _wrap_function.<locals>.wrapper(*args, **kwargs)
     45 start = time.perf_counter()
     46 try:
---> 47     res = func(*args, **kwargs)
     48     logger.log_success(
     49         module_name, class_name, function_name, time.perf_counter() - start, signature
     50     )
     51     return res
File /databricks/spark/python/pyspark/sql/dataframe.py:1073, in DataFrame.show(self, n, truncate, vertical)
    984 def show(self, n: int = 20, truncate: Union[bool, int] = True, vertical: bool = False) -> None:
    985     """
    986     Prints the first ``n`` rows of the DataFrame to the console.
    987 
   (...)
   1071     name | This is a super l...
   1072     """
-> 1073     print(self._show_string(n, truncate, vertical))
File /databricks/spark/python/pyspark/sql/dataframe.py:1091, in DataFrame._show_string(self, n, truncate, vertical)
   1085     raise PySparkTypeError(
   1086         error_class="NOT_BOOL",
   1087         message_parameters={"arg_name": "vertical", "arg_type": type(vertical).__name__},
   1088     )
   1090 if isinstance(truncate, bool) and truncate:
-> 1091     return self._jdf.showString(n, 20, vertical)
   1092 else:
   1093     try:
File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1355, in JavaMember.__call__(self, *args)
   1349 command = proto.CALL_COMMAND_NAME +\
   1350     self.command_header +\
   1351     args_command +\
   1352     proto.END_COMMAND_PART
   1354 answer = self.gateway_client.send_command(command)
-> 1355 return_value = get_return_value(
   1356     answer, self.gateway_client, self.target_id, self.name)
   1358 for temp_arg in temp_args:
   1359     if hasattr(temp_arg, "_detach"):
File /databricks/spark/python/pyspark/errors/exceptions/captured.py:263, in capture_sql_exception.<locals>.deco(*a, **kw)
    260 from py4j.protocol import Py4JJavaError
    262 try:
--> 263     return f(*a, **kw)
    264 except Py4JJavaError as e:
    265     converted = convert_exception(e.java_exception)
File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))



Isn't it strange that the original error: `Name or service not known` is a DNS error?
Pointing to a wrong hostname somewhere?

**Comment by ag-ramachandran** [comment]
@pregress , looks like the notion of a ForceDistributed is not valid against the Kusto database in LAWS. Here is a fully complete example of the code

```scala
%scala
val subscription = ""
val resource_group = "x_getblobwebuxxx"
val log_analytics_workspace = "managed-x"
val accessToken=""




import com.microsoft.kusto.spark.datasource.{TransientStorageParameters,TransientStorageCredentials}

val storage2 = new TransientStorageParameters(Array(new TransientStorageCredentials("https://estdc.blob.core.windows.net/esientstorage?sp=racwl&st=2025-04-17T05:30:21Z&se=a&spr=https&sv=2024-11-04&sr=c&sig=b")))


val  df = spark.read.format("com.microsoft.kusto.spark.datasource") 
    .option("kustoCluster", s"https://ade.loganalytics.io/subscriptions/$subscription/resourceGroups/$resource_group/providers/Microsoft.OperationalInsights/workspaces/$log_analytics_workspace")
    .option("kustoDatabase", log_analytics_workspace)
    .option("kustoQuery", "AppRequests") 
    .option("managedIdentityAuth", "true")
    .option("readMode", "ForceDistributedMode") 
    .option("transientStorage", storage2.toInsecureString) 
    .option("managedIdentityClientId", "2fca3bc2-75d6-4f8f-9c78-e19363d07135")
    .load()
```

This will result in a export not supported scenario

![Image](https://github.com/user-attachments/assets/55a1b79f-d52c-49a8-9d0d-deb765c770fe)



That leaves the option of using a normal mode only

![Image](https://github.com/user-attachments/assets/e56d4ac0-8eef-48ba-aacc-4ee3fe546e4f)

    .option("readMode", "ForceSingleMode") 

Now,  if you have the right export limits configured , the spark connector can be forced to use the single mode so that any timeout or row counts will be ignored and query executed directly without exporting to storage and reading into a DF. I am not sure if Kusto query limits apply to LogAnalytics, in which case you would have to take help from the engg. teams in Log Analytics
