### ISSUE TITLE
Null Pointer exception while using pyspark to write to kusto

### ISSUE THREAD

**Issue by omkar9194** [Azure/azure-kusto-spark#45]
Using pyspark on databricks( version 5 with python version 3), to write a dataframe to a pre-existing kusto table. Getting a null pointer exception

dataset.write. \
  format("com.microsoft.kusto.spark.datasource"). \
  option("kustoCluster",cluster). \
  option("kustoDatabase",database). \
  option("kustoTable", table). \
  option("kustoAADClientID",clientId). \
  option("kustoClientAADClientPassword",clientPassword). \
  option("kustoAADAuthorityID",authorityId). \
  save()
**Error Logs**
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1805396934751416> in <module>()
----> 1 dataset.write.   format("com.microsoft.kusto.spark.datasource").   option("kustoCluster",cluster).   option("kustoDatabase",database).   option("kustoTable", table).   option("kustoAADClientID",clientId).   option("kustoClientAADClientPassword",clientPassword).   option("kustoAADAuthorityID",authorityId).   save()

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    732             self.format(format)
    733         if path is None:
--> 734             self._jwrite.save()
    735         else:
    736             self._jwrite.save(path)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o269.save.
: java.lang.NullPointerException
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.getTaskInputMetrics$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.beginUpdateFilesystemSQLMetrics$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:631)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.foreach(WholeStageCodegenExec.scala:629)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.foldLeft(WholeStageCodegenExec.scala:629)
	at com.microsoft.kusto.spark.datasink.KustoWriter$.serializeRows(KustoWriter.scala:285)
	at com.microsoft.kusto.spark.datasink.KustoWriter$.ingestRowsIntoKusto(KustoWriter.scala:158)
	at com.microsoft.kusto.spark.datasink.KustoWriter$$anonfun$ingestToTemporaryTableByWorkers$1.apply(KustoWriter.scala:224)
	at com.microsoft.kusto.spark.datasink.KustoWriter$$anonfun$ingestToTemporaryTableByWorkers$1.apply(KustoWriter.scala:224)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by mmolaro** [comment]
I also got this problem with essentially the same scenario on the latest beta 1.0.2 using databricks. Previous release works okay for me with a small table.

Is there a dependency issue? Fat jars for kusto data and kusto ingest weren't provided with this latest update so I assume it is expected to work with the previously released versions.

**Comment by michazag** [comment]
Hi Omkar.

This may be the issue documented in https://github.com/Azure/azure-kusto-spark/blob/dev/docs/CHANGELIST.md#known-issues-and-tips.
I didn’t root cause the issue and don’t have  a perfect fix yet, but disabling ‘wholestage code generator’ will hopefully solve it:

spark.conf.set("spark.sql.codegen.wholeStage","false")

Please try it and let me know if it helped.

Regards,
Michael

**Comment by michazag** [comment]
Hi Mark.

WRT Null Pointer – please see my answer to Omkar.
WRT Java libraries – no, the old ones won’t work, you should use 1.0.0-BETA-04 version for both.
The reason they are omitted from the Release<https://github.com/Azure/azure-kusto-spark/releases/tag/1.0.0-Beta-02> on GH is that these libraries can now be installed directly from maven.
Here is the relevant (slightly updated) section from README.md - dependencies section<https://github.com/Azure/azure-kusto-spark/blob/dev/README.md#dependencies>.

Dependencies
Spark Kusto connector takes dependency on Kusto Data Client Library<https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-data> and Kusto Ingest Client Library<https://mvnrepository.com/artifact/com.microsoft.azure.kusto/kusto-ingest>, available on maven repository. When Key Vault based authentication<file:///C:/GitHub/azure-kusto-spark/Authentication.md> is used, there is an additional dependency on Microsoft Azure SDK For Key Vault<https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault>.
Note: When working with Databricks, Kusto connector requires Kusto java client libraries (and azure key-vault library if used) to be installed. This can be done by accessing Databricks Create Library -> Maven and specifying the following coordinates:

  *   com.microsoft.azure.kusto:kusto-data:1.0.0-BETA-04
  *   com.microsoft.azure.kusto:kusto-ingest:1.0.0-BETA-04
Regards,
Michael
