### ISSUE TITLE
getSystemClipboard error

### ISSUE THREAD

**Issue by elainfavourite** [Azure/azure-kusto-spark#49]
I'm trying to get authenticated using Device token method. My code is run on a scala notebook on Azure DataBricks
My Code:
val authorityId = "72f988bf-86f1-41af-91ab-2d7cd011db47" // For microsoft applications, typically "72f988bf-86f1-41af-91ab-2d7cd011db47"
val cluster = "Wdgeventstore"
val database = "Webster"
val table = "ServerMetadata"

val df = sqlContext.read.format("com.microsoft.kusto.spark.datasource")
  .option(KustoOptions.KUSTO_CLUSTER, cluster)
  .option(KustoOptions.KUSTO_DATABASE, database)
  .option(KustoOptions.KUSTO_AAD_AUTHORITY_ID, authorityId)
  .option(KustoOptions.KUSTO_QUERY, "ServerMetadata | take 10")
  .load()
I hit the following error:
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:309)
	at com.microsoft.kusto.spark.utils.DeviceAuthentication$.acquireAccessTokenUsingDeviceCodeFlow(DeviceAuthentication.scala:29)
	at com.microsoft.kusto.spark.utils.KustoDataSourceUtils$.parseSourceParameters(KustoDataSourceUtils.scala:138)
	at com.microsoft.kusto.spark.datasource.DefaultSource.createRelation(DefaultSource.scala:101)

**Comment by ohadbitt** [comment]
This is a known issue - i guess it happened for something had changed in databricks .. a fix is already pushed on the 'dev' brench and will soon be on master
