### ISSUE TITLE
Error in acquiring ApplicationAccessToken

### ISSUE THREAD

**Issue by little-eyes** [Azure/azure-kusto-spark#58]
Hi,

I'm trying to write a dataframe into kusto table, but I got into some authentication issues like below.

My simple code to call the write API. Any idea what happened? I used my AAD account and generate the corresponding secrets from Azure portal.

```python
df.write. \
  format("com.microsoft.kusto.spark.datasource"). \
  option("kustoCluster", "xxxxxxx"). \
  option("kustoDatabase", "xxxxxxxx"). \
  option("kustoTable", "xxxxxxxx"). \
  option("kustoAADClientID", "xxxxxxx"). \
  option("kustoClientAADClientPassword", "xxxxxxxxxx"). \
  option("kustoAADAuthorityID", "xxxxxxxx"). \
  save()
```

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-3272437402474536> in <module>()
----> 1 df.write.   format("com.microsoft.kusto.spark.datasource").   option("kustoCluster", "https://wdgeventstore.kusto.windows.net").   option("kustoDatabase", "CoreData").   option("kustoTable", "WExpInteractionDetection").   option("kustoAADClientID", "167846e2-2119-42fe-bb76-f1289857acdc").   option("kustoClientAADClientPassword", "******").   option("kustoAADAuthorityID", "72f988bf-86f1-41af-91ab-2d7cd011db47").   save()

/databricks/spark/python/pyspark/sql/readwriter.py in save(self, path, format, mode, partitionBy, **options)
    732             self.format(format)
    733         if path is None:
--> 734             self._jwrite.save()
    735         else:
    736             self._jwrite.save(path)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o684.save.
: com.microsoft.azure.kusto.data.exceptions.DataServiceException: Error in acquiring ApplicationAccessToken
	at com.microsoft.azure.kusto.data.AadAuthenticationHelper.acquireToken(AadAuthenticationHelper.java:238)
	at com.microsoft.azure.kusto.data.AadAuthenticationHelper.acquireAccessToken(AadAuthenticationHelper.java:82)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:73)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:45)
	at com.microsoft.azure.kusto.data.ClientImpl.execute(ClientImpl.java:41)
	at com.microsoft.kusto.spark.datasink.KustoWriter$.cleanupTempTables(KustoWriter.scala:121)
	at com.microsoft.kusto.spark.datasink.KustoWriter$.write(KustoWriter.scala:72)
	at com.microsoft.kusto.spark.datasource.DefaultSource.createRelation(DefaultSource.scala:31)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:72)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:88)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:143)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$5.apply(SparkPlan.scala:183)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:114)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:114)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:690)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:690)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withCustomExecutionEnv$1.apply(SQLExecution.scala:99)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:228)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:85)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:158)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:690)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:290)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:284)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ohadbitt** [comment]
Please make sure that the application has the roles described [in the docs](https://github.com/Azure/azure-kusto-spark/blob/dev/docs/KustoSink.md#Authentication)
you can add this line to see more logs:
sc._jvm.com.microsoft.kusto.spark.utils.KustoDataSourceUtils.setLoggingLevel("all")

or if you run it from databricks - look at the driver logs

**Comment by ohadbitt** [comment]
closed for solving directly by mail

**Comment by jansantora** [comment]
Hi @ohadbitt , would you mind sharing the solution here, I am having exactly the same issue. My code stopped working form one day to another with no changes on my end.

**Comment by ohadbitt** [comment]
Hi - this is old - in current versions  the error should reflect the reason
